name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "Děkujeme za pull request, každopádně tento repozitář pull requesty nepřijímá, jelikož se jedná o mirror."
